=== ItAllCanW8/Task8/resources/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/devices"
        xmlns:tns="http://www.example.com/devices" elementFormDefault="qualified">

    <element name="devices" type="tns:Devices"/>
    <complexType name="Devices">
        <sequence>
            <element name="device" type="tns:Device" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Device">
        <sequence>
            <element name="name" type="string"/>
            <element name="origin" type="string"/>
            <element name="price" type="tns:Price"/>
            <element name="type" type="tns:Type"/>
            <element name="critical" type="boolean"/>
        </sequence>
        <attribute name="device_id" type="ID" use="required"/>
        <attribute name="market_launch_date" type="dateTime" default="2010-01-01T00:00:00"/>
    </complexType>

    <simpleType name="Price">
      <restriction base="integer">
        <minInclusive value="1"/>
        <maxInclusive value="9999"/>
      </restriction>
    </simpleType>

    <complexType name="Type">
        <sequence>
            <element name="peripheral" type="boolean"/>
            <element name="power_consumption" type="integer"/>
            <element name="cooler_present" type="boolean"/>
            <element name="group_of_devices" type="tns:GroupOfDevices"/>
            <element name="port" type="tns:Port"/>
        </sequence>
    </complexType>

    <simpleType name="GroupOfDevices">
        <restriction base="string">
            <enumeration value="multimedia"/>
            <enumeration value="input/otput"/>
            <enumeration value="CPU"/>
            <enumeration value="RAM"/>
        </restriction>
    </simpleType>

    <simpleType name="Port">
        <restriction base="string">
            <enumeration value="COM"/>
            <enumeration value="USB"/>
            <enumeration value="LPT"/>
            <enumeration value="none"/>
        </restriction>
    </simpleType>

</schema>

=== ItAllCanW8/Task8/target/classes/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/devices"
         xsi:schemaLocation="http://www.example.com/banks devices.xsd">

   <device device_id="device_1">
      <name>GeForce RTX 2060</name>
      <origin>China</origin>
      <price>2250</price>
      <type>
         <peripheral>true</peripheral>
         <power_consumption>200</power_consumption>
         <cooler_present>true</cooler_present>
         <group_of_devices>multimedia</group_of_devices>
         <port>none</port>
      </type>
      <critical>false</critical>
   </device>

   <device device_id="device_2" market_launch_date="2021-07-07T00:00:00">
      <name>Ryzen 5 3600</name>
      <origin>China</origin>
      <price>450</price>
      <type>
         <peripheral>false</peripheral>
         <power_consumption>65</power_consumption>
         <cooler_present>true</cooler_present>
         <group_of_devices>CPU</group_of_devices>
         <port>none</port>
      </type>
      <critical>true</critical>
   </device>

   <device device_id="device_3">
      <name>Crucial Ballistix Sport LT</name>
      <origin>China</origin>
      <price>140</price>
      <type>
         <peripheral>false</peripheral>
         <power_consumption>3</power_consumption>
         <cooler_present>false</cooler_present>
         <group_of_devices>RAM</group_of_devices>
         <port>none</port>
      </type>
      <critical>true</critical>
   </device>
</devices>
